# fly.toml app configuration file generated for root-web-scraper on 2025-04-03T19:24:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "root-web-scraper"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5123
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
